<?php
$title = 'Accueil';
require_once 'include/doctype.php';
if (isset($_GET['deconnect'])) {unset($_SESSION['login']);}
require_once 'include/index_stylesheet.php';
require_once 'include/header.php';
?>

<section xmlns="http://www.w3.org/1999/html">
        <article></article>
            <div class="box">
                <!-- Start cssSlider.com -->
                <!-- Generated by cssSlider.com 2.1 -->
                <link href="cssslider_files/csss_engine1/style.css" rel="stylesheet">
                <!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
                <!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
                <div class="csslider1 autoplay ">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_0" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_1" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_2" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_3" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_4" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_5" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_6" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_7" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_8" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_9" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_10" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_11" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_12" type="radio">
                    <input name="cs_anchor1" class="cs_anchor slide" id="cs_slide1_13" type="radio">
                    <input name="cs_anchor1" class="cs_anchor" id="cs_play1" type="radio" checked="">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_0" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_1" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_2" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_3" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_4" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_5" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_6" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_7" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_8" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_9" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_10" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_11" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_12" type="radio">
                    <input name="cs_anchor1" class="cs_anchor pause" id="cs_pause1_13" type="radio">
                    <ul>
                        <li class="cs_skeleton"><img style="width: 100%;" src="cssslider_files/csss_images1/image7.jpg"></li>
                        <li class="num0 img slide"> <img title="image7" alt="image7" src="cssslider_files/csss_images1/image7.jpg"></li>
                        <li class="num1 img slide"> <img title="image8" alt="image8" src="cssslider_files/csss_images1/image8.jpg"></li>
                        <li class="num2 img slide"> <img title="image9" alt="image9" src="cssslider_files/csss_images1/image9.jpg"></li>
                        <li class="num3 img slide"> <img title="image10" alt="image10" src="cssslider_files/csss_images1/image10.jpg"></li>
                        <li class="num4 img slide"> <img title="image7" alt="image7" src="cssslider_files/csss_images1/image7_0.jpg"></li>
                        <li class="num5 img slide"> <img title="image12" alt="image12" src="cssslider_files/csss_images1/image12.jpg"></li>
                        <li class="num6 img slide"> <img title="image14" alt="image14" src="cssslider_files/csss_images1/image14.jpg"></li>
                        <li class="num7 img slide"> <img title="classroom-15593_960_720" alt="classroom-15593_960_720" src="cssslider_files/csss_images1/classroom15593_960_720.jpg"></li>
                        <li class="num8 img slide"> <img title="maxresdefault" alt="maxresdefault" src="cssslider_files/csss_images1/maxresdefault.jpg"></li>
                        <li class="num9 img slide"> <img title="school-649388_960_720" alt="school-649388_960_720" src="cssslider_files/csss_images1/school649388_960_720.jpg"></li>
                        <li class="num10 img slide"> <img title="school-649389_960_720" alt="school-649389_960_720" src="cssslider_files/csss_images1/school649389_960_720.jpg"></li>
                        <li class="num11 img slide"> <img title="school-class-401519_960_720" alt="school-class-401519_960_720" src="cssslider_files/csss_images1/schoolclass401519_960_720.jpg"></li>
                        <li class="num12 img slide"> <img title="Smiling-Child-Girl-Wallpaper" alt="Smiling-Child-Girl-Wallpaper" src="cssslider_files/csss_images1/smilingchildgirlwallpaper.jpg"></li>
                        <li class="num13 img slide"> <img title="students-1177716_960_720" alt="students-1177716_960_720" src="cssslider_files/csss_images1/students1177716_960_720.jpg"></li>
                    </ul><div class="cs_engine"><a href="http://cssslider.com">cssslider</a> by cssSlider.com v2.1</div>

                </div>
                <!-- End cssSlider.com -->

            </div>

        <?php
        require_once 'include/footer.php';
        ?>
    </section>
<script src="js/index.js"></script>
<script>
    var Terminator = Object.create(Skynet);
</script>
<?php
require_once 'include/endFile.php';
?>

